/* Edita aquí la dedicatoria y los textos. No requiere compilación. */
window.TRIBUTE = {
  letter: [
    'Hoy quiero regalarte algo que se parezca a lo que siento por ti: admiración, gratitud y un amor enorme.',
    'Al recorrer tu trayectoria, pienso en la mujer que ha construido su camino en la función fiscal. Pero, al pensar en ti, la palabra más importante siempre será la misma: mamá.',
    'Gracias por tu amor y por la fuerza con la que me inspiras. Este pequeño homenaje es una manera de decirte cuánto significas para mí y lo feliz que me hace celebrar tu vida.',
    'Deseo que este nuevo año te regale salud, tranquilidad, motivos para reír y tiempo para disfrutar de todo lo que amas. Que te sientas querida, acompañada y celebrada, hoy y siempre.'
  ],
  signature: 'Con todo mi amor,\npara ti, mamá.',
  wishes: [
    '¡Feliz cumpleaños, mamá! Que nunca te falten motivos para sonreír.',
    'Que este nuevo año te regale salud, calma y momentos hermosos.',
    'Que cada abrazo te recuerde cuánto te queremos.',
    'Hoy celebramos tu vida. Siempre celebramos tenerte.'
  ],
  milestones: {
    '1994': { title: '28.ª Fiscalía Provincial Penal de Lima', description: 'Una etapa documentada de tu trayectoria en el Ministerio Público: la designación en este despacho figura en la Resolución 743-94-MP-FN, del 9 de diciembre de 1994.', source: 'Según el informe aportado, pp. 3 y 6.' },
    '1999': { title: 'Una función especializada', description: 'La Resolución 148-99-MP-CEMP te designó fiscal ad hoc para investigaciones y procesos por terrorismo iniciados desde el 12 de marzo de 1999, conservando tu despacho ordinario.', source: 'Según el informe aportado, pp. 3, 5 y 6; Resolución 148-99-MP-CEMP.' },
    '2008': { title: '20.ª Fiscalía Provincial Penal de Lima', description: 'Un expediente del Tribunal Constitucional documenta tu ejercicio en la Vigésima Fiscalía Provincial Penal de Lima en septiembre de 2008, una etapa posterior de tu carrera fiscal.', source: 'Según el informe aportado, pp. 4 y 6; Exp. 02552-2009-PHC/TC.' },
    '2012': { title: '26.ª Fiscalía Provincial Penal de Lima', description: 'La documentación del Tribunal Constitucional te identifica como fiscal provincial de la Vigésima Sexta Fiscalía Provincial Penal de Lima en 2012.', source: 'Según el informe aportado, pp. 4 y 6; Exp. 00479-2013-PHC/TC.' },
    '2021': { title: 'Santiago de Surco–Barranco', description: 'Un listado referido al 8 de septiembre de 2021 te registra en el 1.er Despacho Provincial Penal de la Primera Fiscalía Corporativa Penal de Santiago de Surco–Barranco, Lima Centro.', source: 'Según el informe aportado, pp. 2 y 5. Es una adscripción histórica, no una confirmación del cargo actual.' }
  },
  chronology: [
    { date: '1994–1995', title: 'Primeras referencias documentales localizadas', text: 'El informe identifica la designación del 9 de diciembre de 1994 en la 28.ª Fiscalía Provincial Penal de Lima, por la Resolución 743-94-MP-FN. También menciona las resoluciones 617-94 y 688-95, cuyos objetos completos no pudo recuperar. Estos registros no establecen el inicio absoluto de la carrera.', links: [['Norma de 2002 que recoge las designaciones anteriores', 'https://vlex.com.pe/vid/provisionales-fiscalias-provinciales-penales-31451651']] },
    { date: '1999–2000', title: 'Fiscal ad hoc en materia de terrorismo', text: 'Designación mediante la Resolución 148-99-MP-CEMP del 10 de marzo de 1999, con competencia sobre investigaciones y procesos iniciados desde el 12 de marzo y conservando el despacho ordinario. Una norma de licencia temporal vuelve a identificarla en ambas funciones. La referencia a la Resolución 160-2000 tiene contenido parcial en el informe.', links: [['Resolución publicada en El Peruano, reproducida en Datos Perú', 'https://www.datosperu.org/directorio-de-normas-legales-del-peru-1999-marzo-11-03-1999-pagina-33.php']] },
    { date: '2002–2004', title: 'Proceso de ratificación y amparo', text: 'El CNM no la ratificó en octubre de 2002 y el Ministerio Público dio por concluidas sus designaciones. En enero de 2003 interpuso amparo. El Tribunal Constitucional lo declaró infundado el 13 de mayo de 2004, dejando a salvo su derecho a volver a postular a la magistratura.', links: [['Tribunal Constitucional · Exp. 0569-2004-AA/TC', 'https://www.tc.gob.pe/jurisprudencia/2004/00569-2004-AA.pdf']] },
    { date: '2003', title: 'Testimonio conservado en el LUM', text: 'El Lugar de la Memoria conserva una entrevista del 9 de julio de 2003, catalogada como entrevista a una exfiscal en terrorismo. El informe no atribuye la dirección de otros casos a partir de las palabras clave del archivo.', links: [['Archivo del Lugar de la Memoria', 'https://lum.cultura.pe/cdi/video/entrevista-exvocal-maria-del-pilar-peralta']] },
    { date: '2006', title: 'Fecha administrativa de ingreso registrada', text: 'Un listado institucional de 2021 consigna el 5 de mayo de 2006 como fecha de ingreso. Dado el ejercicio previo, el informe interpreta que podría corresponder a un reingreso o nuevo vínculo; no localizó la resolución que permita precisar esa interpretación.', links: [['Transcripción del listado referido a septiembre de 2021', 'https://noapaguenlaluz.net/la-lista-de-fiscales-y-administrativos-de-lima-centro-al-8-de-setiembre-del-2021/']] },
    { date: '2008', title: '20.ª Fiscalía Provincial Penal de Lima', text: 'Un expediente constitucional la identifica como fiscal de la Vigésima Fiscalía Provincial Penal de Lima en septiembre de 2008. El registro documenta su ejercicio posterior al proceso de ratificación.', links: [['Tribunal Constitucional · Exp. 02552-2009-PHC/TC', 'https://www.tc.gob.pe/jurisprudencia/2009/02552-2009-HC%20Resolucion.html']] },
    { date: '2011–2012', title: '26.ª Fiscalía Provincial Penal de Lima', text: 'La documentación constitucional la identifica como fiscal provincial de la Vigésima Sexta Fiscalía Provincial Penal de Lima, a cargo de la investigación 87-2011. Se recoge como referencia del despacho que ocupaba, sin atribuir resultados no documentados.', links: [['Tribunal Constitucional · Exp. 00479-2013-PHC/TC', 'https://www.tc.gob.pe/jurisprudencia/2013/00479-2013-HC%20Resolucion.html']] },
    { date: '2015–2017', title: 'Investigación del Sodalicio y revisión posterior', text: 'Como titular de la 26.ª Fiscalía, investigó denuncias vinculadas al Sodalicio y realizó diligencias en Roma en octubre de 2016. En enero de 2017 dispuso el archivo; en marzo, una fiscalía superior declaró nula esa decisión y ordenó reabrir el caso en otro despacho. La cobertura de agosto informó una suspensión de 30 días, susceptible de impugnación. El informe no pudo verificar el resultado definitivo del procedimiento disciplinario.', links: [['Andina · Diligencias en Roma, 2016', 'https://andina.pe/agencia/noticia-fiscal-investiga-caso-del-sodalicio-inicia-diligencias-roma-634799.aspx'], ['RPP · Revisión superior, 2017', 'https://rpp.pe/lima/judiciales/fiscal-superior-declara-nula-la-resolucion-que-ordena-el-archivo-el-caso-sodalicio-noticia-1040693'], ['El Comercio · Información sobre la suspensión', 'https://elcomercio.pe/lima/sucesos/sodalicio-suspenden-fiscal-archivo-caso-falta-denuncias-noticia-448930-noticia/']] },
    { date: '2021', title: 'Fiscalía Corporativa Penal de Santiago de Surco–Barranco', text: 'El listado referido al 8 de septiembre de 2021 la registra como fiscal provincial del 1.er Despacho Provincial Penal de la Primera Fiscalía Corporativa Penal de Santiago de Surco–Barranco, Distrito Fiscal de Lima Centro. El informe accedió a una transcripción de una respuesta de transparencia.', links: [['Listado transcrito de Lima Centro', 'https://noapaguenlaluz.net/la-lista-de-fiscales-y-administrativos-de-lima-centro-al-8-de-setiembre-del-2021/']] },
    { date: '2025–2026', title: 'Última referencia institucional del informe', text: 'El informe refiere su nombre en una relación de costo total anual del Ministerio Público fechada el 1 de enero de 2025, sin enlace directo al archivo. No encontró un directorio o resolución de 2026 que confirme su despacho vigente. Esta página no deduce un cargo actual a partir del registro histórico.', links: [] }
  ]
};
