/* Edita aquí la dedicatoria y los textos. No requiere compilación. */
window.TRIBUTE = {
  letter: [
    'Hoy quiero regalarte algo que se parezca a lo que siento por ti: admiración, gratitud y un amor enorme.',
    'Al recorrer tu trayectoria, pienso en la mujer que ha construido su camino en la función fiscal. Pero, al pensar en ti, la palabra más importante siempre será la misma: mamá.',
    'Gracias por tu amor y por la fuerza con la que me inspiras. Este pequeño homenaje es una manera de decirte cuánto significas para mí y lo feliz que me hace celebrar tu vida.',
    'Deseo que este nuevo año te regale salud, tranquilidad, motivos para reír y tiempo para disfrutar de todo lo que amas. Que te sientas querida, acompañada y celebrada, hoy y siempre.'
  ],
  signature: 'Con todo mi amor,\npara ti, mamá.',
  wishes: [
    '¡Feliz cumpleaños, mamá! Que nunca te falten motivos para sonreír.',
    'Que este nuevo año te regale salud, calma y momentos hermosos.',
    'Que cada abrazo te recuerde cuánto te queremos.',
    'Hoy celebramos tu vida. Siempre celebramos tenerte.'
  ],
  milestones: {
    '1990': { title: 'Ingreso a la carrera fiscal', description: 'Ingresaste como Fiscal Adjunta a la Fiscalía Provincial en lo Penal de Lima y juramentaste el 7 de agosto de 1990.', source: 'Resolución Suprema 285-90-JUS; Resolución CNM 081-2007-PCNM.' },
    '1994': { title: '28.ª Fiscalía Provincial Penal de Lima', description: 'Una etapa documentada de tu trayectoria en el Ministerio Público: la designación en este despacho figura en la Resolución 743-94-MP-FN, del 9 de diciembre de 1994.', source: 'Según el informe aportado, pp. 3 y 6.' },
    '1999': { title: 'Fiscal Ad Hoc para casos de terrorismo', description: 'La Resolución 148-99-MP-CEMP te designó como Fiscal Ad Hoc para conocer de manera exclusiva investigaciones y procesos por terrorismo iniciados desde el 12 de marzo de 1999, conservando tu despacho ordinario.', source: 'Resolución 148-99-MP-CEMP, publicada el 11 de marzo de 1999.' },
    '2006': { title: 'Reincorporación y 26.ª Fiscalía', description: 'La Fiscalía de la Nación dispuso tu reincorporación como Fiscal Provincial Titular y tu designación en el despacho de la Vigésima Sexta Fiscalía Provincial en lo Penal de Lima.', source: 'Resolución de la Fiscalía de la Nación 480-2006-MP-FN, del 3 de mayo de 2006.' },
    '2012': { title: '26.ª Fiscalía Provincial Penal de Lima', description: 'La documentación del Tribunal Constitucional te identifica como fiscal provincial de la Vigésima Sexta Fiscalía Provincial Penal de Lima en 2012.', source: 'Según el informe aportado, pp. 4 y 6; Exp. 00479-2013-PHC/TC.' },
    '2021': { title: 'Santiago de Surco–Barranco', description: 'Un listado referido al 8 de septiembre de 2021 te registra en el 1.er Despacho Provincial Penal de la Primera Fiscalía Corporativa Penal de Santiago de Surco–Barranco, Lima Centro.', source: 'Según el informe aportado, pp. 2 y 5. Es una adscripción histórica, no una confirmación del cargo actual.' }
  },
  chronology: [
    { date: '1990', title: 'Ingreso a la carrera fiscal', text: 'La resolución de ratificación del CNM de 2007 señala que ingresó a la carrera fiscal mediante la Resolución Suprema 285-90-JUS, del 19 de julio de 1990, como Fiscal Adjunta a la Fiscalía Provincial en lo Penal de Lima. Juramentó el 7 de agosto de ese año.', links: [['Resolución CNM 081-2007-PCNM, vía SPIJ', 'https://spij.minjus.gob.pe/Normas/textos/180907T.pdf']] },
    { date: '1994–1995', title: 'Primeras referencias documentales localizadas', text: 'El informe identifica la designación del 9 de diciembre de 1994 en la 28.ª Fiscalía Provincial Penal de Lima, por la Resolución 743-94-MP-FN. También menciona las resoluciones 617-94 y 688-95, cuyos objetos completos no pudo recuperar. Estos registros no establecen el inicio absoluto de la carrera.', links: [['Norma de 2002 que recoge las designaciones anteriores', 'https://vlex.com.pe/vid/provisionales-fiscalias-provinciales-penales-31451651']] },
    { date: '1999–2000', title: 'Fiscal Ad Hoc para casos de terrorismo', text: 'La Resolución 148-99-MP-CEMP, del 10 de marzo de 1999, la designó expresamente como Fiscal Ad Hoc para conocer de manera exclusiva las investigaciones policiales y los procesos por delito de terrorismo que se iniciaran desde el 12 de marzo, manteniendo su despacho en la 28.ª Fiscalía. En octubre de 2000, otra resolución la identifica como Fiscal Provincial Penal Ad Hoc para casos de Terrorismo y autoriza su asistencia a diligencias fuera de Lima. Una resolución de marzo de 2000 también confirma que mantenía funciones en los casos de terrorismo de 1999.', links: [['Resolución 148-99-MP-CEMP, publicada en El Peruano', 'https://www.datosperu.org/directorio-de-normas-legales-del-peru-1999-marzo-11-03-1999-pagina-33.php'], ['Resolución 704-2000-MP-CEMP, publicada en El Peruano', 'https://www.datosperu.org/directorio-de-normas-legales-del-peru-2000-octubre-10-10-2000-pagina-9.php'], ['Resolución 168-2000-MP-CEMP, publicada en El Peruano', 'https://www.datosperu.org/directorio-de-normas-legales-del-peru-2000-marzo-04-03-2000-pagina-19.php']] },
    { date: '2001', title: 'Referencia periodística como fiscal antiterrorismo', text: 'En una entrevista publicada por El Comercio sobre la tragedia de Mesa Redonda, ocurrida el 29 de diciembre de 2001, la nota la identifica como fiscal antiterrorismo y relata que estaba de turno, asumió el caso y trabajó durante casi dos días en el levantamiento de cadáveres. La pieza periodística aporta contexto público adicional, aunque no reemplaza las resoluciones de designación.', links: [['El Comercio · Testimonios de Mesa Redonda', 'https://elcomercio.pe/lima/mesa-redonda-testimonios-tragedia-cumple-15-anos-155562-noticia/']] },
    { date: '2002–2004', title: 'Proceso de ratificación y amparo', text: 'El CNM no la ratificó en octubre de 2002 y el Ministerio Público dio por concluidas sus designaciones. En enero de 2003 interpuso amparo. El Tribunal Constitucional lo declaró infundado el 13 de mayo de 2004, dejando a salvo su derecho a volver a postular a la magistratura.', links: [['Tribunal Constitucional · Exp. 0569-2004-AA/TC', 'https://www.tc.gob.pe/jurisprudencia/2004/00569-2004-AA.pdf']] },
    { date: '2003', title: 'Testimonio conservado en el LUM', text: 'El Lugar de la Memoria conserva una entrevista del 9 de julio de 2003, catalogada como entrevista a una exfiscal en terrorismo. El informe no atribuye la dirección de otros casos a partir de las palabras clave del archivo.', links: [['Archivo del Lugar de la Memoria', 'https://lum.cultura.pe/cdi/video/entrevista-exvocal-maria-del-pilar-peralta']] },
    { date: '2006–2007', title: 'Reincorporación como Fiscal Provincial Titular', text: 'La Resolución 480-2006-MP-FN dejó constancia de la rehabilitación de títulos vinculada al acuerdo de solución amistosa y dispuso reincorporarla como Fiscal Provincial Titular en lo Penal del Distrito Judicial de Lima, designándola en la 26.ª Fiscalía. En agosto de 2007, el CNM ratificó a la magistrada en el cargo.', links: [['Resolución de reincorporación 480-2006-MP-FN, vía SPIJ', 'https://spij.minjus.gob.pe/Normas/textos/040506T.pdf'], ['Resolución de ratificación 081-2007-PCNM, vía SPIJ', 'https://spij.minjus.gob.pe/Normas/textos/180907T.pdf']] },
    { date: '2008', title: '20.ª Fiscalía Provincial Penal de Lima', text: 'Un expediente constitucional la identifica como fiscal de la Vigésima Fiscalía Provincial Penal de Lima en septiembre de 2008. El registro documenta su ejercicio posterior al proceso de reincorporación.', links: [['Tribunal Constitucional · Exp. 02552-2009-PHC/TC', 'https://www.tc.gob.pe/jurisprudencia/2009/02552-2009-HC%20Resolucion.html']] },
    { date: '2011–2012', title: '26.ª Fiscalía Provincial Penal de Lima', text: 'La documentación constitucional la identifica como fiscal provincial de la Vigésima Sexta Fiscalía Provincial Penal de Lima, a cargo de la investigación 87-2011. Se recoge como referencia del despacho que ocupaba, sin atribuir resultados no documentados.', links: [['Tribunal Constitucional · Exp. 00479-2013-PHC/TC', 'https://www.tc.gob.pe/jurisprudencia/2013/00479-2013-HC%20Resolucion.html']] },
    { date: '2015–2017', title: 'Investigación del Sodalicio y revisión posterior', text: 'Como titular de la 26.ª Fiscalía, investigó denuncias vinculadas al Sodalicio y realizó diligencias en Roma en octubre de 2016. En enero de 2017 dispuso el archivo; en marzo, una fiscalía superior declaró nula esa decisión y ordenó reabrir el caso en otro despacho. La cobertura de agosto informó una suspensión de 30 días, susceptible de impugnación. El informe no pudo verificar el resultado definitivo del procedimiento disciplinario.', links: [['Andina · Diligencias en Roma, 2016', 'https://andina.pe/agencia/noticia-fiscal-investiga-caso-del-sodalicio-inicia-diligencias-roma-634799.aspx'], ['RPP · Revisión superior, 2017', 'https://rpp.pe/lima/judiciales/fiscal-superior-declara-nula-la-resolucion-que-ordena-el-archivo-el-caso-sodalicio-noticia-1040693'], ['El Comercio · Información sobre la suspensión', 'https://elcomercio.pe/lima/sucesos/sodalicio-suspenden-fiscal-archivo-caso-falta-denuncias-noticia-448930-noticia/']] },
    { date: '2021', title: 'Fiscalía Corporativa Penal de Santiago de Surco–Barranco', text: 'El listado referido al 8 de septiembre de 2021 la registra como fiscal provincial del 1.er Despacho Provincial Penal de la Primera Fiscalía Corporativa Penal de Santiago de Surco–Barranco, Distrito Fiscal de Lima Centro. El informe accedió a una transcripción de una respuesta de transparencia.', links: [['Listado transcrito de Lima Centro', 'https://noapaguenlaluz.net/la-lista-de-fiscales-y-administrativos-de-lima-centro-al-8-de-setiembre-del-2021/']] },
    { date: '2025–2026', title: 'Última referencia institucional del informe', text: 'El informe refiere su nombre en una relación de costo total anual del Ministerio Público fechada el 1 de enero de 2025, sin enlace directo al archivo. No encontró un directorio o resolución de 2026 que confirme su despacho vigente. Esta página no deduce un cargo actual a partir del registro histórico.', links: [] }
  ]
};
